### PR TITLE
Add post for Fellowship 2017

### PR DESCRIPTION
**Pull request by jennysivapalan**
Should we apply the workforus domain on all the job roles?

cc @sallygoble @mchv @philwills

### CODE REVIEW

**Comment by mchv** [comment]
👍 
> Should we apply the workforus domain on all the job roles?
I am for it, I found the design better!

**Comment by jennysivapalan** [comment]
* Used for workforus links
* Removed `Software Engineer - tools, automation, process"` role as no longer exists on workforus. @sallygoble Is this correct or do we need to reopen the role?

* Side note: @fgauchet do you want to add https://workforus.theguardian.com/jobs/kin0000si/ ?

**Comment by fgauchet** [comment]
@jennysivapalan Yes please

**Comment by jennysivapalan** [comment]
Going to merge this. @fgauchet if you have a blurb to add please feel free to add it as separate PR. 

@sallygoble if you want me to re-instate `Software Engineer - tools, automation, process` we can work on this next week.

**Pull request merged**
