### PR TITLE
Replace developer team video with new version

### PR DESCRIPTION
**Pull request by arausuy**
Replace old video with more recent developer conversations - fits with the same dimensions as the original video at a variety of browser widths.

image

image

image

### CODE REVIEW

**Comment by johnduffell** [comment]
a manager can add you to 
image
then you will be able to merge PRs and push branches

**Comment by franziskas** [comment]
@arausy this should work now

**Comment by johnduffell** [comment]
thanks for doing this! 👍 🏅 🌟

**Comment by johnduffell** [comment]
PS the cache time is 10 minutes, so sometimes it doesn't appear very quickly

**Comment by franziskas** [comment]
@arausuy has this been released? can't see them on the `gh-pages` branch

**Comment by arausuy** [comment]
@franziskas Yup - release ~5 minutes ago - just waiting for cache to expire

**Pull request merged**
