### PR TITLE
Please merge job changes

### PR DESCRIPTION
**Pull request by sallygoble**
Added SET job description

### CODE REVIEW

**Comment by mattandrews** [comment]
No issues with the code, but I love the job description itself (the last part in particular). :+1:

**Comment by sallygoble** [comment]
Thanks :) Am I OK to merge this myself? Can someone deploy once merged? Is it a riffraff deploy I can do myself?

**Comment by mattandrews** [comment]
Yeah – if you merge it yourself, then you can deploy it yourself too if you fancy it! If you just `cd` (in terminal) into the folder the code is in, then run `./release.sh` it should do it automatically – it's all done by Github, no need for Magenta/RiffRaff. Give me a shout if you need a hand!

**Comment by gidsg** [comment]
> We are looking someone

You are missing a 'for' there!

**Pull request merged**
