### PR TITLE
add Source to list of open source projects

### PR DESCRIPTION
**Pull request by webb04**
## What does this change?
Updated list of open source projects to include Source.

## How to test
Should see the new project at https://developers.theguardian.com/open-source.html and the link should take you to GitHub.

### CODE REVIEW

**Comment by JamieB-gu** [comment]
DCR but not AR? 😢

Also agree that Janus might be a good one @adamnfish? And what about the Grid @akash1810?

**Comment by adamnfish** [comment]
I'll address @JamieB-gu's comment in a moment, since my answers are a little off topic for this PR.

Directly addressing this PR, as a change it looks sensible to me but it might be worth chasing up with the authors or maintainers of the repositories being removed. This gives them the opportunity to check they aren't aware of good reasons that justified their inclusion in the first place?

A little more generally, I think this "open source" list is quite out of date. It might be worth us starting a document or thread where we can look at what is there and what is missing as a with our colleagues, but that doesn't necessarily need to hold up this PR.

------

I am tagged in the Janus-app question. My view is that as the main author of Janus-app I am the person in the world least qualified to decide whether it warrants this kind of publicity on behalf of the department.

However, I can say that from my point of view including Janus-app here would be OK in theory now that it has been open-sourced.

The fact that Janus-app and the Grid have come up straight away adds weight to the question of whether this PR should be treated as the start of a conversation about what we as a department feel best represents us? I'll not muddy the waters here with additional thoughts, but I'll be happy to take part in a wider review if that happens.

**Comment by webb04** [comment]
The two contributors for the `guss` project have left I believe and "reusable components across Guardian web products" sounds a lot like the current Source project.

@rtyley I selected the `gu-who` project as it seemed less active, but I realise it might still be used frequently? Source and DCR are frontend focused so it might be good to keep `gu-who` to show a better balance of engineering projects?

**Comment by rtyley** [comment]
> @rtyley I selected the `gu-who` project as it seemed less active, but I realise it might still be used frequently?

It does seem to be used fairly widely, but it is indeed not that actively developed right now, happy for it to be removed!

**Review by dskamiotis — APPROVED** [review]

**Pull request merged**
