### PR TITLE
Add ScalaX talk

### PR DESCRIPTION
**Pull request by nicl**
Shameless self-promotion!

Note, I haven't tested this and don't really know how.

@jennysivapalan

### CODE REVIEW

**Comment by jennysivapalan** [comment]
Notes to test locally are on the README! 
This looks fine to me though 👍

**Comment by jamespamplin** [comment]
@nicl tested locally and removed an excess comma in  	66ad89f for you :)

**Comment by rrees** [comment]
@nicl did you really find the README too complicated?

**Comment by nicl** [comment]
@rrees no, my initial comment was slightly joking. Jenny had done an appeal for people to add stuff so I added my PR quickly in response.

**Comment by nicl** [comment]
@jamespamplin thanks!

**Pull request merged**
